name: CI
on:
  push:
  pull_request:
env:
  VulkanSDKVersion: 1.2.162.1
jobs:    
  linux-build:
    runs-on: ubuntu-latest
    env:
      BuildDocEnabled: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
      VULKAN_SDK: $GITHUB_WORKSPACE/../$VulkanSDKVersion/x86_64
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{env.VULKAN_SDK}}
        key: VulkanSdk${{env.VulkanSDKVersion}}ExtractedLinux
    - name: Download & Extract Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget --no-cookies -O ../vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}.tar.gz https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/linux/vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}.tar.gz?u=
        tar -zxf ../vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}.tar.gz -C ../
    - name: Extract branch name
      shell: bash
      run: |
        echo ${GITHUB_REF##*/}
        echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/*/}
      id: extract_branch
    - name: VSG Checkout (If Remote Branch Exists)
      if: github.event_name == 'push'
      id: has-remote-branch
      uses: actions/checkout@v2
      with:
        repository: vsg-dev/VulkanSceneGraph
        path: vsg
        ref: ${{steps.extract_branch.outputs.branch}}
      continue-on-error: true
    - name: VSG Checkout (Master)
      uses: actions/checkout@v2
      with:
        repository: vsg-dev/VulkanSceneGraph
        path: vsg
      if: steps.has-remote-branch.outcome == 'failure'
    - name: VSG Build and Install
      run: |
        cd vsg
        cmake -D Vulkan_INCLUDE_DIR="${{env.VULKAN_SDK}}/include" \
          -D Vulkan_LIBRARY="${{env.VULKAN_SDK}}/lib/libvulkan.so" .
        make -j 2
        sudo make install
    - name: vsgExamples Build and Install
      run: |
        cd main
        cmake -D Vulkan_INCLUDE_DIR="${{env.VULKAN_SDK}}/include" \
          -D Vulkan_LIBRARY="${{env.VULKAN_SDK}}/lib/libvulkan.so" .
        make -j 2
        sudo make install
 